### PR TITLE
Add fileglobs support for uploading more than one spec

### PR DESCRIPTION
**Pull request by jimbydamonk**
There are times when we have more than one spec we need to upload. 
I am not sure if this is the correct approach but it works.

### CODE REVIEW

**Comment by tonglil** [comment]
Is your choice to use goroutines because you want to upload as many specs as possible, regardless if there is an error with one of them?

Or is it ok to error out if there is an error in one of the spec's upload?

**Comment by jimbydamonk** [comment]
I would rather have as many upload as possible. But I could go either way. The real need is to be able to upload more than one at a time. If something happens after some get published, the overall build should fail so it can be retried.

**Comment by tonglil** [comment]
Ok I see.

Typically the only failures that occur is due to the spec being invalid (eg yaml cannot be parsed into json), in which case retrying would not change anything until the file is fixed.

I am rewriting this plugin as there's some issues with it currently wrt authentication & redirects. The current implementation is to upload in the defined order until something errors out.

**Comment by jimbydamonk** [comment]
That would be fine.

**Pull request closed without merging**
